name: Python Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Install CUDA and NVIDIA drivers
      run: |
        sudo apt-get update
        sudo apt-get install -y nvidia-cuda-toolkit nvidia-driver-460

    - name: Lint with pylint
      run: |
        pylint src/get_hugging_face_embeding.py

    - name: Test with pytest
      run: |
        pytest